spring.application.name=consumer
server.port=8082

# Postgres (local Docker)
spring.datasource.url=jdbc:postgresql://localhost:5433/notification_consumer
spring.datasource.username=notification
spring.datasource.password=notification

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
